// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeApqVsP0Ebha5jwujHYbiUqgyvQrn11Q',
    appId: '1:393924540734:web:d6bade04951b0d7648946f',
    messagingSenderId: '393924540734',
    projectId: 'fir-project-c1e8f',
    authDomain: 'fir-project-c1e8f.firebaseapp.com',
    storageBucket: 'fir-project-c1e8f.appspot.com',
    measurementId: 'G-8678E46EEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj8RPCbfikgnPiNEKtFoXEN3qE5_MnHeE',
    appId: '1:393924540734:android:36734f67b59357ca48946f',
    messagingSenderId: '393924540734',
    projectId: 'fir-project-c1e8f',
    storageBucket: 'fir-project-c1e8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi94nIxu2ACB-KHNWejsjL09YTTiewxXQ',
    appId: '1:393924540734:ios:7980585bdd05532448946f',
    messagingSenderId: '393924540734',
    projectId: 'fir-project-c1e8f',
    storageBucket: 'fir-project-c1e8f.appspot.com',
    iosClientId: '393924540734-ui47h5vksc6rlo9outs3jkrbag8mmceu.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportFriends',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi94nIxu2ACB-KHNWejsjL09YTTiewxXQ',
    appId: '1:393924540734:ios:7980585bdd05532448946f',
    messagingSenderId: '393924540734',
    projectId: 'fir-project-c1e8f',
    storageBucket: 'fir-project-c1e8f.appspot.com',
    iosClientId: '393924540734-ui47h5vksc6rlo9outs3jkrbag8mmceu.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportFriends',
  );
}
